steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker build -t us-east1-docker.pkg.dev/arcane-geode-289112/image-registry -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_DATABASE_URL=$$DATABASE_URL .
  secretEnv: ['DATABASE_URL']

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'us-east1-docker.pkg.dev/arcane-geode-289112/image-registry',
    ]

availableSecrets:
  secretManager:
  - versionName: projects/821295140891/secrets/orders-db-url/versions/1
    env: 'DATABASE_URL'