version: '3'

services:
  orders-db:
    container_name: pg_database
    image: postgres:17.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: superSecret
      POSTGRES_DB: orders